-- Assignment 2
-- Data for table `account`

-- Query 1
INSERT INTO public.account (account_firstname, account_lastname, account_email, account_password)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

-- Query 2
UPDATE public.account
SET account_type = 'Admin'
WHERE account_id = 1;

-- Query 3
DELETE FROM public.account
WHERE account_id = 1;

-- Query 4
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'the small interiors', 'a huge interior')
WHERE inv_id = 10;

SELECT inv_description FROM public.inventory
WHERE inv_id = 10;

-- Query 5
SELECT i.inv_make, i.inv_model, c.classification_name
FROM inventory i
INNER JOIN classification c ON i.classification_id = c.classification_id
WHERE c.classification_name = 'Sport';

-- Query 6
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

SELECT inv_image, inv_thumbnail FROM public.inventory;

-- Week 6 Enhancement Project
CREATE TABLE public.review (
  review_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  review_text TEXT NOT NULL,
  review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  inv_id INT NOT NULL REFERENCES inventory(inv_id),
  account_id INT NOT NULL REFERENCES account(account_id)
);

ALTER TABLE review
ADD COLUMN review_rating INTEGER CHECK (review_rating >= 1 AND review_rating <= 5);
